CREATE TABLE country
(
    id BIGINT generated by default as identity PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    continent VARCHAR(255) NOT NULL
);

CREATE TABLE host
(
    id        BIGINT generated by default as identity PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    surname    VARCHAR(255) NOT NULL,
    country_id BIGINT,
    CONSTRAINT fk_host_country FOREIGN KEY (country_id) REFERENCES country (id) on delete cascade on update cascade
);

CREATE TYPE category_enum AS ENUM ('ROOM', 'HOUSE', 'FLAT', 'APARTMENT', 'HOTEL', 'MOTEL');

CREATE TABLE housing
(
    id BIGINT generated by default as identity PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category category_enum NOT NULL,
    host BIGINT,
    numRooms INTEGER,
    CONSTRAINT fk_housing_host FOREIGN KEY (host) REFERENCES host (id) on delete cascade on update cascade
);

CREATE TYPE role_enum AS ENUM ('ROLE_USER', 'ROLE_HOST');

CREATE TABLE booking_users
(
    username                   VARCHAR(255) PRIMARY KEY,
    password                   VARCHAR(255) NOT NULL,
    name                       VARCHAR(255) NOT NULL,
    surname                    VARCHAR(255) NOT NULL,
    is_account_non_expired     BOOLEAN DEFAULT TRUE,
    is_account_non_locked      BOOLEAN DEFAULT TRUE,
    is_credentials_non_expired BOOLEAN DEFAULT TRUE,
    is_enabled                 BOOLEAN DEFAULT TRUE,
    role                       role_enum    NOT NULL
);